### ISSUE TITLE
Feature engineering question

### ISSUE THREAD

**Issue by LinX-1998** [daweicheng/antifraud#4]
how can I use the example_data.csv to get the train feature data and train label data about model cnn_att_3d?

**Comment by xiangsheng1325** [comment]
The implementation of feature engineering can be found at `antifraud/feature_engineering/data_engineering.py`.

Note that `example_data.csv` contains few entries due to privacy limitations.

**Comment by Janet180** [comment]
I couldn't find the source code for Graph Neural Network for Fraud Detection via Spatial-temporal Attention. STAGN doesn't seem to be in the antifraud/methods.
