### ISSUE TITLE
你好阅读论文和代码的时候有些问题请教

### ISSUE THREAD

**Issue by AtwoodDuan** [daweicheng/antifraud#5]
您好，

拜读了您和您团队的论文以及相关代码，收获非常大，您和您的团队，在这个领域的理解很深，但是在理解网络结构的公式和论文中有一些小问题想请教您和您的团队。

![image](https://user-images.githubusercontent.com/19813460/123048386-ec207180-d430-11eb-9d2a-934a63124fdc.png)
主要集中在attention layer部分
1.公式(1)中的 a1,t 是标量么，还是矩阵，如果是矩阵的话维度是多少，  
2.如果是a1,t 标量，公式(1)进行了求和运算，但是等式右边为时间切片的求和，最后得到的张量应该和时间切片的shape一致吧，但是文中提到reshape the output rept into tensor format rept ∈ RN1×N2×N3。是不是不太一致。
3.公式(2)中Wt的张量的shape分别是多少。如果a1,t是标量，则gt(Wt, X(t, :, :))也应该是标量，但是代码中好像不是。

4. 如果a1,t 不是标量，会感觉softmax的部分没沿着垂直切片的维度进行softmax？
5. 注意到公式(2)W有下标t，是指每一个时间切片都配一个W么，但是代码里面只初始化了一个W，如果按照代码理解是不是用下标1更好一点。
6. 注意到代码中将softmax后的结果reduce_sum，这一步似乎会导致alpha_i中所有数值都为1
![image](https://user-images.githubusercontent.com/19813460/123051889-cd23de80-d434-11eb-91fa-fd6f57b1578b.png)

如果有任何指点，我将不胜感激。

感谢！

**Comment by xiangsheng1325** [comment]
你好，感谢你对我们工作的关注。

1. 公式(1)中的`$a_{1,t}$`是标量。
代码中为了加速运算，将attention权重并行计算了，因此代码实现中没有出现标量。
2. 公式(1)演示的是单个时间切片下的输出，为避免歧义，可以将原文`rept`理解为`rept(t,:,:)`。
3. 各层的权重维度均在create_placeholder函数中定义完毕。
4. （Not applicable）
5. 公式2的下标t并未用错，代码实现中实际上并行计算time_attention weight，看起来像只定义了一个。
6. （Not applicable）
